blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/terrytz/BetterStage/discussions
    about: Ask questions and start discussions here instead of opening an issue.
  - name: Feature Ideas
    url: https://github.com/terrytz/BetterStage/discussions/categories/ideas
    about: Suggest new features and improvements.
